### ISSUE TITLE
Declare runtime dependencies correctly

### ISSUE THREAD

**Issue by PikachuEXE** [brigade/db-query-matchers#24]
These 2 seem to be runtime dependencies, not just development dependencies
- `activesupport` - [required in code](https://github.com/brigade/db-query-matchers/blob/master/lib/db_query_matchers.rb#L5)
- `rspec` - [required in code](https://github.com/brigade/db-query-matchers/blob/master/lib/db_query_matchers/make_database_queries.rb#L1)

**Comment by trotzig** [comment]
You're right. Would you be willing to put together a PR for this? I think it would make sense to make the dependency an optimistic one so that we don't force duplicate `activesupport` and `rspec` versions on to users of the gem. If you think it's worth it, we could try figuring out from what version this gem works, and do something like 

```rb
spec.add_runtime_dependency 'activesupport', '>= 4.0.2'
```
(`4.0.2` is just an example, and the minimum version we need is likely something different.)

We could also just leave them open-ended, and use whatever is available:
```rb
spec.add_runtime_dependency 'activesupport'
```
